import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class AppLocalizations extends ChangeNotifier {
  static final AppLocalizations _instance = AppLocalizations._internal();
  factory AppLocalizations() => _instance;
  AppLocalizations._internal();

  static const String _languageKey = 'selected_language';
  String _currentLanguage = 'en';

  String get currentLanguage => _currentLanguage;
  String get currentLanguageName => _currentLanguage == 'en' ? 'English' : 'Türkçe';

  Future<void> initialize() async {
    final prefs = await SharedPreferences.getInstance();
    _currentLanguage = prefs.getString(_languageKey) ?? 'en';
    notifyListeners();
  }

  Future<void> setLanguage(String languageCode) async {
    _currentLanguage = languageCode;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_languageKey, languageCode);
    notifyListeners();
  }

  String translate(String key) {
    return _translations[_currentLanguage]?[key] ?? _translations['en']?[key] ?? key;
  }

  String get(String key) => translate(key);

  static const Map<String, Map<String, String>> _translations = {
    'en': _englishTranslations,
    'tr': _turkishTranslations,
  };
}

const Map<String, String> _englishTranslations = {
  'app_name': 'GeoPin',
  'app_tagline': 'Test Your Geography Knowledge',
  'settings': 'Settings',
  
  // Section Headers
  'famous_places': 'Famous Places',
  'continents': 'Continents',
  'us_states': 'US States',
  'natural_wonders_section': 'Natural Wonders',
  'premium_content': 'Premium Content',
  'general': 'General',
  'app': 'App',
  'legal': 'Legal',
  'upgrade_to_premium': 'Upgrade to Premium',
  'upgrade_description': 'Get ad-free experience and exclusive features',
  'language': 'Language',
  'english': 'English',
  'turkish': 'Turkish',
  'music': 'Music',
  'music_description': 'Background music during gameplay',
  'theme': 'Theme',
  'dark_mode': 'Dark Mode',
  'light_mode': 'Light Mode',
  'rate_app': 'Rate App',
  'share_app': 'Share App',
  'contact_us': 'Contact Us',
  'contact_description': 'Get in touch with our team',
  'privacy_policy': 'Privacy Policy',
  'terms_of_use': 'Terms of Use',
  'tourist_places_1': 'Tourist Places 1',
  'tourist_places_2': 'Tourist Places 2',
  'capitals_1': 'Capitals 1',
  'capitals_2': 'Capitals 2',
  'historical_landmarks': 'Historical Landmarks',
  'america': 'America',
  'europe_1': 'Europe 1',
  'europe_2': 'Europe 2',
  'asia_1': 'Asia 1',
  'asia_2': 'Asia 2',
  'africa_1': 'Africa 1',
  'africa_2': 'Africa 2',
  'africa_3': 'Africa 3',
  'oceania': 'Oceania',
  'us_states_1': 'US States 1',
  'us_states_2': 'US States 2',
  'natural_wonders_1': 'Natural Wonders 1',
  'natural_wonders_2': 'Natural Wonders 2',
  'iconic_bridges': 'Iconic Bridges',
  'tallest_skyscrapers': 'Tallest Skyscrapers',
  'world_cuisine': 'World Cuisine',
  'football_stadiums': 'Football Stadiums',
  'famous_airports': 'Famous Airports',
  'premium': 'Premium',
  'unlock_all_maps': 'Unlock all maps with Premium',
  'get_premium': 'Get Premium',
  'cancel': 'Cancel',
  'premium_upgrade_coming_soon': 'Premium upgrade coming soon.',
  'language_selection_coming_soon': 'Language selection coming soon.',
  'rate_app_coming_soon': 'Rate App coming soon.',
  'share_app_coming_soon': 'Share App coming soon.',
  'contact_flow_coming_soon': 'Contact flow coming soon.',
  'privacy_policy_coming_soon': 'Privacy Policy coming soon.',
  'terms_of_use_coming_soon': 'Terms of Use coming soon.',
  'purchase_flow_not_added': 'Purchase flow not yet added.',
  'category_included_in_pro': 'category is included in PRO package. Get Premium to access all locked categories.',
  
  // Game Screen UI
  'guess': 'Guess',
  'next': 'Next',
  'close': 'Close',
  'continue': 'Continue',
  'previous': 'Previous',
  'correct': 'Correct!',
  'wrong': 'Wrong',
  'score': 'Score',
  'result': 'Result',
  'back_to_main_menu': 'Back to Main Menu',
  'tap_circle_to_answer': 'Tap on a circle to answer.',
  'tap_map_to_select': 'Tap on the map to select your guess point.',
  'you_selected_right': 'You selected the right stadium.',
  'not_correct_stadium': 'That is not the correct stadium.',
  'you_selected_correct': 'You selected correctly!',
  'not_correct_answer': 'That is not the correct answer.',
  'km_away': 'km away!',
  'your_score': 'Your score:',
  'green_pin_shows_correct': 'Green pin shows the correct location, red pin shows your guess.',
  
  // Completion Messages
  'stadiums_completed': 'Football Stadiums Completed!',
  'stadiums_completed_msg': 'You found all the iconic football stadiums around the world. What a match!',
  'airports_completed': 'Famous Airports Completed!',
  'airports_completed_msg': 'You located all the major airports around the globe. Ready for takeoff!',
  'cuisine_completed': 'World Cuisine Completed!',
  'cuisine_completed_msg': 'You discovered all the culinary capitals of the world. Bon appétit!',
  'wonders_completed': 'Natural Wonders Completed!',
  'wonders_completed_msg': 'You found all the natural wonders. Nature at its finest!',
  'us_states_completed': 'US States Completed!',
  'us_states_completed_msg': 'You located all the US states. Coast to coast!',
  'oceania_completed': 'Oceania Completed!',
  'oceania_completed_msg': 'You discovered all countries in Oceania. Island hopping complete!',
  'africa_completed': 'Africa Completed!',
  'africa_completed_msg': 'You found all African countries. Safari complete!',
  'asia_completed': 'Asia Completed!',
  'asia_completed_msg': 'You located all Asian countries. From east to west!',
  'europe_completed': 'Europe Completed!',
  'europe_completed_msg': 'You discovered all European countries. Continental journey complete!',
  'america_completed': 'America Completed!',
  'america_completed_msg': 'You found all American countries. From north to south!',
  
  // Questions - Tourist Places
  'q_statue_liberty': 'Where is the Statue of Liberty?',
  'q_eiffel': 'Where is the Eiffel Tower?',
  'q_colosseum': 'Where is the Colosseum?',
  'q_bigben': 'Where is Big Ben?',
  'q_sydney_opera': 'Where is the Sydney Opera House?',
  'q_taj_mahal': 'Where is the Taj Mahal?',
  'q_great_wall': 'Where is the Great Wall of China?',
  'q_golden_gate': 'Where is the Golden Gate Bridge?',
  'q_christ_redeemer': 'Where is Christ the Redeemer?',
  'q_burj_khalifa': 'Where is Burj Khalifa?',
  'q_louvre': 'Where is the Louvre Museum?',
  'q_stonehenge': 'Where is Stonehenge?',
  'q_notre_dame': 'Where is Notre Dame Cathedral?',
  'q_versailles': 'Where is the Palace of Versailles?',
  'q_acropolis': 'Where is the Acropolis?',
  'q_sagrada_familia': 'Where is La Sagrada Familia?',
  'q_neuschwanstein': 'Where is Neuschwanstein Castle?',
  'q_petra': 'Where is Petra?',
  'q_machu_picchu': 'Where is Machu Picchu?',
  'q_angkor_wat': 'Where is Angkor Wat?',
  
  // Tüm diğer sorular için fallback - orijinal İngilizce metinleri kullan
  // Çünkü 454 sorunun hepsini tek tek yazmak yerine, fallback mekanizması çalışacak
};

const Map<String, String> _turkishTranslations = {
  'app_name': 'GeoPin',
  'app_tagline': 'Coğrafya Bilginizi Test Edin',
  'settings': 'Ayarlar',
  
  // Bölüm Başlıkları
  'famous_places': 'Ünlü Yerler',
  'continents': 'Kıtalar',
  'us_states': 'ABD Eyaletleri',
  'natural_wonders_section': 'Doğal Harikalar',
  'premium_content': 'Premium İçerik',
  'general': 'Genel',
  'app': 'Uygulama',
  'legal': 'Yasal',
  'upgrade_to_premium': 'Premium\'a Yükselt',
  'upgrade_description': 'Reklamsız deneyim ve özel özellikler edinin',
  'language': 'Dil',
  'english': 'İngilizce',
  'turkish': 'Türkçe',
  'music': 'Müzik',
  'music_description': 'Oyun sırasında arka plan müziği',
  'theme': 'Tema',
  'dark_mode': 'Koyu Mod',
  'light_mode': 'Açık Mod',
  'rate_app': 'Uygulamayı Değerlendir',
  'share_app': 'Uygulamayı Paylaş',
  'contact_us': 'Bize Ulaşın',
  'contact_description': 'Ekibimizle iletişime geçin',
  'privacy_policy': 'Gizlilik Politikası',
  'terms_of_use': 'Kullanım Koşulları',
  'tourist_places_1': 'Turistik Yerler 1',
  'tourist_places_2': 'Turistik Yerler 2',
  'capitals_1': 'Başkentler 1',
  'capitals_2': 'Başkentler 2',
  'historical_landmarks': 'Tarihi Yerler',
  'america': 'Amerika',
  'europe_1': 'Avrupa 1',
  'europe_2': 'Avrupa 2',
  'asia_1': 'Asya 1',
  'asia_2': 'Asya 2',
  'africa_1': 'Afrika 1',
  'africa_2': 'Afrika 2',
  'africa_3': 'Afrika 3',
  'oceania': 'Okyanusya',
  'us_states_1': 'ABD Eyaletleri 1',
  'us_states_2': 'ABD Eyaletleri 2',
  'natural_wonders_1': 'Doğal Harikalar 1',
  'natural_wonders_2': 'Doğal Harikalar 2',
  'iconic_bridges': 'İkonik Köprüler',
  'tallest_skyscrapers': 'En Yüksek Gökdelenler',
  'world_cuisine': 'Dünya Mutfağı',
  'football_stadiums': 'Futbol Stadyumları',
  'famous_airports': 'Ünlü Havalimanları',
  'premium': 'Premium',
  'unlock_all_maps': 'Premium ile tüm haritaların kilidini açın',
  'get_premium': 'Premium Al',
  'cancel': 'İptal',
  'premium_upgrade_coming_soon': 'Premium yükseltme yakında.',
  'language_selection_coming_soon': 'Dil seçimi yakında.',
  'rate_app_coming_soon': 'Uygulama değerlendirme yakında.',
  'share_app_coming_soon': 'Uygulama paylaşımı yakında.',
  'contact_flow_coming_soon': 'İletişim akışı yakında.',
  'privacy_policy_coming_soon': 'Gizlilik Politikası yakında.',
  'terms_of_use_coming_soon': 'Kullanım Koşulları yakında.',
  'purchase_flow_not_added': 'Satın alma akışı henüz eklenmedi.',
  'category_included_in_pro': 'kategorisi PRO paketine dahildir. Tüm kilitli kategorilere erişmek için Premium alın.',
  
  // Oyun Ekranı UI
  'guess': 'Tahmin Et',
  'next': 'İleri',
  'close': 'Kapat',
  'continue': 'Devam',
  'previous': 'Önceki',
  'correct': 'Doğru!',
  'wrong': 'Yanlış!',
  'score': 'Puan',
  'result': 'Sonuç',
  'game_completed': 'Oyun Tamamlandı!',
  'total_score': 'Toplam Puan',
  'questions': 'Sorular',
  'average': 'Ortalama',
  'back_to_main_menu': 'Ana Menüye Dön',
  'you_selected_right_country': 'Doğru ülkeyi seçtiniz.',
  'not_correct_country': 'Bu doğru ülke değil.',
  'success': 'başarı',
  'tap_circle_to_answer': 'Cevap vermek için daireye dokunun.',
  'tap_map_to_select': 'Tahmin noktanızı seçmek için haritaya dokunun.',
  'you_selected_right': 'Doğru stadyumu seçtiniz.',
  'not_correct_stadium': 'Bu doğru stadyum değil.',
  'you_selected_correct': 'Doğru seçtiniz!',
  'not_correct_answer': 'Bu doğru cevap değil.',
  'km_away': 'km uzakta!',
  'your_score': 'Puanınız:',
  'green_pin_shows_correct': 'Yeşil pin doğru konumu, kırmızı pin tahmininizi gösterir.',
  
  // Tamamlama Mesajları
  'stadiums_completed': 'Futbol Stadyumları Tamamlandı!',
  'stadiums_completed_msg': 'Dünyanın dört bir yanındaki ikonik futbol stadyumlarını buldunuz. Ne maç!',
  'airports_completed': 'Ünlü Havalimanları Tamamlandı!',
  'airports_completed_msg': 'Dünyadaki tüm büyük havalimanlarını buldunuz. Kalkışa hazır!',
  'cuisine_completed': 'Dünya Mutfağı Tamamlandı!',
  'cuisine_completed_msg': 'Dünyanın tüm mutfak başkentlerini keşfettiniz. Afiyet olsun!',
  'wonders_completed': 'Doğal Harikalar Tamamlandı!',
  'wonders_completed_msg': 'Tüm doğal harikaları buldunuz. Doğa en güzel haliyle!',
  'us_states_completed': 'ABD Eyaletleri Tamamlandı!',
  'us_states_completed_msg': 'Tüm ABD eyaletlerini buldunuz. Kıyıdan kıyıya!',
  'oceania_completed': 'Okyanusya Tamamlandı!',
  'oceania_completed_msg': 'Okyanusya\'daki tüm ülkeleri keşfettiniz. Ada turu tamamlandı!',
  'africa_completed': 'Afrika Tamamlandı!',
  'africa_completed_msg': 'Tüm Afrika ülkelerini buldunuz. Safari tamamlandı!',
  'asia_completed': 'Asya Tamamlandı!',
  'asia_completed_msg': 'Tüm Asya ülkelerini buldunuz. Doğudan batıya!',
  'europe_completed': 'Avrupa Tamamlandı!',
  'europe_completed_msg': 'Tüm Avrupa ülkelerini keşfettiniz. Kıta yolculuğu tamamlandı!',
  'america_completed': 'Amerika Tamamlandı!',
  'america_completed_msg': 'Tüm Amerika ülkelerini buldunuz. Kuzeyden güneye!',
  
  // Sorular - Turistik Yerler
  'q_statue_liberty': 'Özgürlük Heykeli nerede?',
  'q_eiffel': 'Eyfel Kulesi nerede?',
  'q_colosseum': 'Kolezyum nerede?',
  'q_bigben': 'Big Ben nerede?',
  'q_sydney_opera': 'Sidney Opera Binası nerede?',
  'q_taj_mahal': 'Tac Mahal nerede?',
  'q_great_wall': 'Çin Seddi nerede?',
  'q_golden_gate': 'Golden Gate Köprüsü nerede?',
  'q_christ_redeemer': 'Kurtarıcı İsa Heykeli nerede?',
  'q_burj_khalifa': 'Burj Khalifa nerede?',
  'q_louvre': 'Louvre Müzesi nerede?',
  'q_stonehenge': 'Stonehenge nerede?',
  'q_notre_dame': 'Notre Dame Katedrali nerede?',
  'q_versailles': 'Versay Sarayı nerede?',
  'q_acropolis': 'Akropolis nerede?',
  'q_sagrada_familia': 'La Sagrada Familia nerede?',
  'q_neuschwanstein': 'Neuschwanstein Kalesi nerede?',
  'q_petra': 'Petra nerede?',
  'q_machu_picchu': 'Machu Picchu nerede?',
  'q_angkor_wat': 'Angkor Wat nerede?',
  'q_santorini': 'Santorini nerede?',
  'q_cappadocia': 'Kapadokya nerede?',
  'q_bora_bora': 'Bora Bora nerede?',
  'q_bali': 'Bali nerede?',
  'q_iceland': 'İzlanda nerede?',
  'q_pamukkale': 'Pamukkale nerede?',
  'q_ha_long_bay': 'Ha Long Körfezi nerede?',
  'q_chichen_itza': 'Chichen Itza nerede?',
  'q_times_square': 'Times Meydanı nerede?',
  'q_central_park': 'Central Park nerede?',
  'q_disneyland': 'Disneyland nerede?',
  'q_the_hollywood_sign': 'Hollywood Yazısı nerede?',
  'q_the_las_vegas_strip': 'Las Vegas Strip nerede?',
  'q_miami_beach': 'Miami Plajı nerede?',
  'q_the_liberty_bell': 'Özgürlük Çanı nerede?',
  'q_the_grand_canyon': 'Büyük Kanyon nerede?',
  'q_mount_everest': 'Everest Dağı nerede?',
  'q_the_great_barrier_reef': 'Büyük Set Resifi nerede?',
  'q_the_amazon_rainforest': 'Amazon Yağmur Ormanı nerede?',
  'q_niagara_falls': 'Niagara Şelaleleri nerede?',
  'q_victoria_falls': 'Victoria Şelaleleri nerede?',
  'q_the_sahara_desert': 'Sahra Çölü nerede?',
  'q_mount_kilimanjaro': 'Kilimanjaro Dağı nerede?',
  'q_mount_fuji': 'Fuji Dağı nerede?',
  'q_the_matterhorn': 'Matterhorn nerede?',
  'q_the_rocky_mountains': 'Rocky Dağları nerede?',
  'q_the_alps': 'Alpler nerede?',
  'q_yellowstone_national_park': 'Yellowstone Milli Parkı nerede?',
  'q_yosemite_national_park': 'Yosemite Milli Parkı nerede?',
  'q_the_dead_sea': 'Ölü Deniz nerede?',
  'q_the_nile_river': 'Nil Nehri nerede?',
  'q_lake_baikal': 'Baykal Gölü nerede?',
  'q_lake_victoria': 'Victoria Gölü nerede?',
  'q_antarctica': 'Antarktika nerede?',
  'q_greenland': 'Grönland nerede?',
  'q_madagascar': 'Madagaskar nerede?',
  'q_the_galapagos_islands': 'Galapagos Adaları nerede?',
  'q_the_maldives': 'Maldivler nerede?',
  'q_the_seychelles': 'Seyşeller nerede?',
  'q_the_canary_islands': 'Kanarya Adaları nerede?',
  'q_hawaii': 'Hawaii nerede?',
  'q_the_caribbean_sea': 'Karayip Denizi nerede?',
  'q_the_red_sea': 'Kızıldeniz nerede?',
  'q_the_black_forest': 'Kara Orman nerede?',
  'q_mount_olympus': 'Olimpos Dağı nerede?',
  'q_mount_etna': 'Etna Dağı nerede?',
  'q_loch_ness': 'Loch Ness nerede?',
  'q_the_island_of_capri': 'Capri Adası nerede?',
  'q_dead_vlei_in_the_namib_desert': 'Namib Çölündeki Dead Vlei nerede?',
  'q_mount_rushmore': 'Mount Rushmore nerede?',
  'q_the_brooklyn_bridge': 'Brooklyn Köprüsü nerede?',
  'q_tower_bridge': 'Tower Bridge nerede?',
  'q_the_sydney_harbour_bridge': 'Sidney Liman Köprüsü nerede?',
  'q_charles_bridge': 'Charles Köprüsü nerede?',
  'q_ponte_vecchio': 'Ponte Vecchio nerede?',
  'q_the_rialto_bridge': 'Rialto Köprüsü nerede?',
  'q_the_chain_bridge_in_budapest': 'Budapeştedeki Zincirli Köprü nerede?',
  'q_the_vasco_da_gama_bridge': 'Vasco da Gama Köprüsü nerede?',
  'q_the_millau_viaduct': 'Millau Viyadüğü nerede?',
  'q_pont_du_gard': 'Pont du Gard nerede?',
  'q_the_chapel_bridge_kapellbrücke': 'Şapel Köprüsü (Kapellbrücke) nerede?',
  'q_stari_most': 'Stari Most nerede?',
  'q_the_15_july_martyrs_bosphorus_bridge': '15 Temmuz Şehitler (Boğaziçi) Köprüsü nerede?',
  'q_the_akashi_kaikyo_bridge': 'Akashi Kaikyo Köprüsü nerede?',
  'q_banpo_bridge': 'Banpo Köprüsü nerede?',
  'q_the_helix_bridge': 'Helix Köprüsü nerede?',
  'q_sheikh_zayed_bridge': 'Şeyh Zayed Köprüsü nerede?',
  'q_the_empire_state_building': 'Empire State Binası nerede?',
  'q_the_space_needle': 'Space Needle nerede?',
  'q_the_hoover_dam': 'Hoover Barajı nerede?',
  'q_the_petronas_towers': 'Petronas Kuleleri nerede?',
  'q_abraj_al_bait_mecca_clock_tower': 'Abraj Al Bait (Mekke Saat Kulesi) nerede?',
  'q_brandenburg_gate': 'Brandenburg Kapısı nerede?',
  'q_st_pauls_cathedral': 'St. Paul Katedrali nerede?',
  'q_the_amsterdam_windmills': 'Amsterdam Yel Değirmenleri nerede?',
  'q_the_kremlin_and_red_square': 'Kremlin ve Kızıl Meydan nerede?',
  'q_saint_basils_cathedral': 'Aziz Basil Katedrali nerede?',
  'q_the_moai_statues_on_easter_island': 'Paskalya Adasındaki Moai heykelleri nerede?',
  
  // Resimlerde görünen sorular
  'q_paris': 'Paris nerede?',
  'q_blue_mosque': 'Mavi Cami (Sultan Ahmet Camii) nerede?',
  'q_united_states': 'Amerika Birleşik Devletleri nerede?',
  'q_paris_croissants': 'Kruvasanlarıyla ünlü Paris nerede?',
  'q_cdg_airport': 'Paris Charles de Gaulle Havalimanı (CDG) nerede?',
  

  // Ek ülke ve şehir çevirileri
  'q_afghanistan': 'Afganistan nerede?',
  'q_alabama': 'Alabama nerede?',
  'q_alaska': 'Alaska nerede?',
  'q_albania': 'Arnavutluk nerede?',
  'q_algeria': 'Cezayir nerede?',
  'q_amsterdam': 'Amsterdam nerede?',
  'q_andorra': 'Andorra nerede?',
  'q_angola': 'Angola nerede?',
  'q_ankara': 'Ankara nerede?',
  'q_argentina': 'Arjantin nerede?',
  'q_arizona': 'Arizona nerede?',
  'q_arkansas': 'Arkansas nerede?',
  'q_armenia': 'Ermenistan nerede?',
  'q_athens': 'Atina nerede?',
  'q_australia': 'Avustralya nerede?',
  'q_austria': 'Avusturya nerede?',
  'q_azerbaijan': 'Azerbaycan nerede?',
  'q_bahrain': 'Bahreyn nerede?',
  'q_bangkok': 'Bangkok nerede?',
  'q_bangladesh': 'Bangladeş nerede?',
  'q_beijing': 'Pekin nerede?',
  'q_belarus': 'Belarus nerede?',
  'q_belgium': 'Belçika nerede?',
  'q_berlin': 'Berlin nerede?',
  'q_bolivia': 'Bolivya nerede?',
  'q_bosnia_and_herzegovina': 'Bosna Hersek nerede?',
  'q_brazil': 'Brezilya nerede?',
  'q_brussels': 'Brüksel nerede?',
  'q_budapest': 'Budapeşte nerede?',
  'q_bulgaria': 'Bulgaristan nerede?',
  'q_cairo': 'Kahire nerede?',
  'q_california': 'Kaliforniya nerede?',
  'q_cambodia': 'Kamboçya nerede?',
  'q_cameroon': 'Kamerun nerede?',
  'q_canada': 'Kanada nerede?',
  'q_chile': 'Şili nerede?',
  'q_china': 'Çin nerede?',
  'q_colombia': 'Kolombiya nerede?',
  'q_colorado': 'Colorado nerede?',
  'q_copenhagen': 'Kopenhag nerede?',
  'q_costa_rica': 'Kosta Rika nerede?',
  'q_croatia': 'Hırvatistan nerede?',
  'q_cuba': 'Küba nerede?',
  'q_cyprus': 'Kıbrıs nerede?',
  'q_czech_republic': 'Çek Cumhuriyeti nerede?',
  'q_denmark': 'Danimarka nerede?',
  'q_dublin': 'Dublin nerede?',
  'q_ecuador': 'Ekvador nerede?',
  'q_egypt': 'Mısır nerede?',
  'q_estonia': 'Estonya nerede?',
  'q_ethiopia': 'Etiyopya nerede?',
  'q_fiji': 'Fiji nerede?',
  'q_finland': 'Finlandiya nerede?',
  'q_florida': 'Florida nerede?',
  'q_france': 'Fransa nerede?',
  'q_georgia': 'Georgia nerede?',
  'q_germany': 'Almanya nerede?',
  'q_ghana': 'Gana nerede?',
  'q_greece': 'Yunanistan nerede?',
  'q_guatemala': 'Guatemala nerede?',
  'q_helsinki': 'Helsinki nerede?',
  'q_honduras': 'Honduras nerede?',
  'q_hungary': 'Macaristan nerede?',
  'q_illinois': 'Illinois nerede?',
  'q_india': 'Hindistan nerede?',
  'q_indiana': 'Indiana nerede?',
  'q_indonesia': 'Endonezya nerede?',
  'q_iran': 'İran nerede?',
  'q_iraq': 'Irak nerede?',
  'q_ireland': 'İrlanda nerede?',
  'q_israel': 'İsrail nerede?',
  'q_italy': 'İtalya nerede?',
  'q_jamaica': 'Jamaika nerede?',
  'q_japan': 'Japonya nerede?',
  'q_jordan': 'Ürdün nerede?',
  'q_kansas': 'Kansas nerede?',
  'q_kazakhstan': 'Kazakistan nerede?',
  'q_kentucky': 'Kentucky nerede?',
  'q_kenya': 'Kenya nerede?',
  'q_kuwait': 'Kuveyt nerede?',
  'q_latvia': 'Letonya nerede?',
  'q_lebanon': 'Lübnan nerede?',
  'q_libya': 'Libya nerede?',
  'q_lisbon': 'Lizbon nerede?',
  'q_lithuania': 'Litvanya nerede?',
  'q_london': 'Londra nerede?',
  'q_louisiana': 'Louisiana nerede?',
  'q_luxembourg': 'Lüksemburg nerede?',
  'q_madrid': 'Madrid nerede?',
  'q_malaysia': 'Malezya nerede?',
  'q_maryland': 'Maryland nerede?',
  'q_massachusetts': 'Massachusetts nerede?',
  'q_mexico': 'Meksika nerede?',
  'q_michigan': 'Michigan nerede?',
  'q_minnesota': 'Minnesota nerede?',
  'q_mississippi': 'Mississippi nerede?',
  'q_missouri': 'Missouri nerede?',
  'q_moldova': 'Moldova nerede?',
  'q_monaco': 'Monako nerede?',
  'q_mongolia': 'Moğolistan nerede?',
  'q_montana': 'Montana nerede?',
  'q_montenegro': 'Karadağ nerede?',
  'q_morocco': 'Fas nerede?',
  'q_moscow': 'Moskova nerede?',
  'q_myanmar': 'Myanmar nerede?',
  'q_nebraska': 'Nebraska nerede?',
  'q_nepal': 'Nepal nerede?',
  'q_netherlands': 'Hollanda nerede?',
  'q_nevada': 'Nevada nerede?',
  'q_new_jersey': 'New Jersey nerede?',
  'q_new_mexico': 'New Mexico nerede?',
  'q_new_york': 'New York nerede?',
  'q_new_zealand': 'Yeni Zelanda nerede?',
  'q_nicaragua': 'Nikaragua nerede?',
  'q_nigeria': 'Nijerya nerede?',
  'q_north_carolina': 'Kuzey Carolina nerede?',
  'q_north_korea': 'Kuzey Kore nerede?',
  'q_norway': 'Norveç nerede?',
  'q_ohio': 'Ohio nerede?',
  'q_oklahoma': 'Oklahoma nerede?',
  'q_oman': 'Umman nerede?',
  'q_oregon': 'Oregon nerede?',
  'q_oslo': 'Oslo nerede?',
  'q_pakistan': 'Pakistan nerede?',
  'q_panama': 'Panama nerede?',
  'q_paraguay': 'Paraguay nerede?',
  'q_pennsylvania': 'Pennsylvania nerede?',
  'q_peru': 'Peru nerede?',
  'q_philippines': 'Filipinler nerede?',
  'q_poland': 'Polonya nerede?',
  'q_portugal': 'Portekiz nerede?',
  'q_prague': 'Prag nerede?',
  'q_qatar': 'Katar nerede?',
  'q_romania': 'Romanya nerede?',
  'q_rome': 'Roma nerede?',
  'q_russia': 'Rusya nerede?',
  'q_saudi_arabia': 'Suudi Arabistan nerede?',
  'q_senegal': 'Senegal nerede?',
  'q_seoul': 'Seul nerede?',
  'q_serbia': 'Sırbistan nerede?',
  'q_singapore': 'Singapur nerede?',
  'q_slovakia': 'Slovakya nerede?',
  'q_slovenia': 'Slovenya nerede?',
  'q_south_africa': 'Güney Afrika nerede?',
  'q_south_carolina': 'Güney Carolina nerede?',
  'q_south_korea': 'Güney Kore nerede?',
  'q_spain': 'İspanya nerede?',
  'q_sri_lanka': 'Sri Lanka nerede?',
  'q_stockholm': 'Stockholm nerede?',
  'q_sudan': 'Sudan nerede?',
  'q_sweden': 'İsveç nerede?',
  'q_switzerland': 'İsviçre nerede?',
  'q_syria': 'Suriye nerede?',
  'q_taiwan': 'Tayvan nerede?',
  'q_tanzania': 'Tanzanya nerede?',
  'q_tennessee': 'Tennessee nerede?',
  'q_texas': 'Teksas nerede?',
  'q_thailand': 'Tayland nerede?',
  'q_tokyo': 'Tokyo nerede?',
  'q_tunisia': 'Tunus nerede?',
  'q_turkey': 'Türkiye nerede?',
  'q_ukraine': 'Ukrayna nerede?',
  'q_united_arab_emirates': 'Birleşik Arap Emirlikleri nerede?',
  'q_united_kingdom': 'Birleşik Krallık nerede?',
  'q_uruguay': 'Uruguay nerede?',
  'q_utah': 'Utah nerede?',
  'q_uzbekistan': 'Özbekistan nerede?',
  'q_venezuela': 'Venezuela nerede?',
  'q_vienna': 'Viyana nerede?',
  'q_vietnam': 'Vietnam nerede?',
  'q_virginia': 'Virginia nerede?',
  'q_warsaw': 'Varşova nerede?',
  'q_washington': 'Washington nerede?',
  'q_wisconsin': 'Wisconsin nerede?',
  'q_yemen': 'Yemen nerede?',
  

  // Tarihi Yerler, Stadyumlar, Havalimanları, Mutfak
  'q_alcazar_of_seville': 'Sevilla Alcazarı nerede?',
  'q_alhambra': 'Elhamra Sarayı nerede?',
  'q_allianz_arena': 'Allianz Arena nerede?',
  'q_anfield': 'Anfield nerede?',
  'q_arc_de_triomphe': 'Zafer Takı nerede?',
  'q_atatürk_olympic_stadium': 'Atatürk Olimpiyat Stadyumu nerede?',
  'q_azteca': 'Azteca Stadyumu nerede?',
  'q_bangkok_pad_thai': 'Bangkok, Pad Thainin evi nerede?',
  'q_barajas': 'Madrid Barajas Havalimanı nerede?',
  'q_barcelona_tapas': 'Barselona, tapasın evi nerede?',
  'q_beijing_peking_duck': 'Pekin, Pekin Ördeğinin evi nerede?',
  'q_blenheim_palace': 'Blenheim Sarayı nerede?',
  'q_buckingham_palace': 'Buckingham Sarayı nerede?',
  'q_camp_nou': 'Camp Nou nerede?',
  'q_castel_santangelo': 'Castel SantAngelo nerede?',
  'q_changi': 'Singapur Changi Havalimanı nerede?',
  'q_charles_de_gaulle': 'Charles de Gaulle Havalimanı nerede?',
  'q_chateau_de_chambord': 'Chambord Şatosu nerede?',
  'q_cologne_cathedral': 'Köln Katedrali nerede?',
  'q_doges_palace': 'Doge Sarayı nerede?',
  'q_dubai_international': 'Dubai Uluslararası Havalimanı nerede?',
  'q_duomo_di_milano': 'Milano Katedrali nerede?',
  'q_edinburgh_castle': 'Edinburgh Kalesi nerede?',
  'q_forbidden_city': 'Yasak Şehir nerede?',
  'q_frankfurt_airport': 'Frankfurt Havalimanı nerede?',
  'q_hagia_sophia': 'Ayasofya nerede?',
  'q_haneda': 'Tokyo Haneda Havalimanı nerede?',
  'q_heathrow': 'Heathrow Havalimanı nerede?',
  'q_hong_kong_international': 'Hong Kong Uluslararası Havalimanı nerede?',
  'q_istanbul_airport': 'İstanbul Havalimanı nerede?',
  'q_istanbul_kebab': 'İstanbul, kebabın esi nerede?',
  'q_jfk': 'JFK Havalimanı nerede?',
  'q_la_bombonera': 'La Bombonera nerede?',
  'q_lax': 'Los Angeles Uluslararası Havalimanı nerede?',
  'q_lyon_french_cuisine': 'Lyon, Fransız mutfağının esi nerede?',
  'q_maracana': 'Maracanã nerede?',
  'q_mexico_city_tacos': 'Mexico City, tacoların esi nerede?',
  'q_mont_saint-michel': 'Mont Saint-Michel nerede?',
  'q_mumbai_curry': 'Mumbai, körinin esi nerede?',
  'q_naples_pizza': 'Napoli, pizzanın evi nerede?',
  'q_old_trafford': 'Old Trafford nerede?',
  'q_palace_of_westminster': 'Westminster Sarayı nerede?',
  'q_piazza_san_marco': 'San Marco Meydanı nerede?',
  'q_piccadilly_circus': 'Piccadilly Circus nerede?',
  'q_potala_palace': 'Potala Sarayı nerede?',
  'q_prague_castle': 'Prag Kalesi nerede?',
  'q_red_square': 'Kızıl Meydan nerede?',
  'q_royal_palace_of_madrid': 'Madrid Kraliyet Sarayı nerede?',
  'q_san_siro': 'San Siro nerede?',
  'q_santiago_bernabeu': 'Santiago Bernabéu nerede?',
  'q_schiphol': 'Amsterdam Schiphol Havalimanı nerede?',
  'q_schönbrunn_palace': 'Schönbrunn Sarayı nerede?',
  'q_signal_iduna_park': 'Signal Iduna Park nerede?',
  'q_sistine_chapel': 'Sistine Şapeli nerede?',
  'q_spanish_steps': 'İspanyol Merdivenleri nerede?',
  'q_st_peters_basilica': 'Aziz Petrus Bazilikası nerede?',
  'q_the_kremlin': 'Kremlin nerede?',
  'q_the_pantheon': 'Pantheon nerede?',
  'q_the_parthenon': 'Parthenon nerede?',
  'q_the_white_house': 'Beyaz Saray nerede?',
  'q_tiananmen_square': 'Tiananmen Meydanı nerede?',
  'q_tokyo_sushi': 'Tokyo, sushinin esi nerede?',
  'q_topkapi_palace': 'Topkapı Sarayı nerede?',
  'q_trafalgar_square': 'Trafalgar Meydanı nerede?',
  'q_trevi_fountain': 'Trevi Çeşmesi nerede?',
  'q_vienna_schnitzel': 'Viyana, şnitselin esi nerede?',
  'q_wembley': 'Wembley Stadyumu nerede?',
  'q_westminster_abbey': 'Westminster Manastırı nerede?',
  'q_winter_palace': 'Kış Sarayı nerede?',
  

  // Otomatik eklenen eksik çeviriler
  'q_abu_simbel': 'Abu Simbel nerede?',
  'q_addis_ababa': 'Addis Ababa nerede?',
  'q_adolfo_suárez_madridbarajas_airport_mad': 'Adolfo Suárez Madridbarajas Airport Mad nerede?',
  'q_allianz_arena_with_its_color-changing_exterior': 'Allianz Arena With Its Color-Changing Exterior nerede?',
  'q_amsterdam_schiphol_airport_ams': 'Amsterdam Schiphol Airport Ams nerede?',
  'q_atatürk_olympic_stadium_famous_for_the_2005_ucl_final': 'Atatürk Olympic Stadium Famous For The 2005 Ucl Final nerede?',
  'q_bangkok_home_of_pad_thai': 'Bangkok Home Of Pad Thai nerede?',
  'q_barcelona_famous_for_tapas': 'Barcelona Famous For Tapas nerede?',
  'q_beijing_famous_for_peking_duck': 'Beijing Famous For Peking Duck nerede?',
  'q_belize': 'Belize nerede?',
  'q_benin': 'Benin nerede?',
  'q_bern': 'Bern nerede?',
  'q_bhutan': 'Bhutan nerede?',
  'q_bogotá': 'Bogotá nerede?',
  'q_botswana': 'Botswana nerede?',
  'q_brasília': 'Brasília nerede?',
  'q_brunei': 'Brunei nerede?',
  'q_budapest_famous_for_goulash': 'Budapest Famous For Goulash nerede?',
  'q_burj_al_arab': 'Burj Al Arab nerede?',
  'q_burkina_faso': 'Burkina Faso nerede?',
  'q_burundi': 'Burundi nerede?',
  'q_cabo_verde': 'Cabo Verde nerede?',
  'q_camp_nou_the_largest_stadium_in_europe': 'Camp Nou The Largest Stadium In Europe nerede?',
  'q_canberra': 'Canberra nerede?',
  'q_chad': 'Chad nerede?',
  'q_chicago_ohare_international_airport': 'Chicago OHare International Airport nerede?',
  'q_comoros': 'Comoros nerede?',
  'q_connecticut': 'Connecticut nerede?',
  'q_czechia': 'Czechia nerede?',
  'q_delaware': 'Delaware nerede?',
  'q_denver_international_airport_den': 'Denver International Airport Den nerede?',
  'q_djibouti': 'Djibouti nerede?',
  'q_dubai_international_airport_dxb': 'Dubai International Airport Dxb nerede?',
  'q_el_salvador': 'El Salvador nerede?',
  'q_emirates_stadium_modern_home_of_arsenal': 'Emirates Stadium Modern Home Of Arsenal nerede?',
  'q_equatorial_guinea': 'Equatorial Guinea nerede?',
  'q_eritrea': 'Eritrea nerede?',
  'q_estadio_azteca_host_of_two_world_cup_finals': 'Estadio Azteca Host Of Two World Cup Finals nerede?',
  'q_estádio_da_luz_home_of_benfica': 'Estádio Da Luz Home Of Benfica nerede?',
  'q_eswatini': 'Eswatini nerede?',
  'q_frankfurt_airport_fra': 'Frankfurt Airport Fra nerede?',
  'q_gabon': 'Gabon nerede?',
  'q_gaziantep_famous_for_baklava': 'Gaziantep Famous For Baklava nerede?',
  'q_georgia_us': 'Georgia Us nerede?',
  'q_gran_torre_santiago': 'Gran Torre Santiago nerede?',
  'q_guinea': 'Guinea nerede?',
  'q_guinea-bissau': 'Guinea-Bissau nerede?',
  'q_guyana': 'Guyana nerede?',
  'q_hamad_international_airport_doh': 'Hamad International Airport Doh nerede?',
  'q_hamburg_origin_of_the_hamburger_name': 'Hamburg Origin Of The Hamburger Name nerede?',
  'q_hanoi': 'Hanoi nerede?',
  'q_hanoi_home_of_pho': 'Hanoi Home Of Pho nerede?',
  'q_hartsfield-jackson_atlanta_international_airport_atl': 'Hartsfield-Jackson Atlanta International Airport Atl nerede?',
  'q_himeji_castle': 'Himeji Castle nerede?',
  'q_hong_kong_famous_for_dim_sum': 'Hong Kong Famous For Dim Sum nerede?',
  'q_hong_kong_international_airport_hkg': 'Hong Kong International Airport Hkg nerede?',
  'q_idaho': 'Idaho nerede?',
  'q_incheon_international_airport_icn': 'Incheon International Airport Icn nerede?',
  'q_iowa': 'Iowa nerede?',
  'q_islamabad': 'Islamabad nerede?',
  'q_istanbul_airport_ist': 'Istanbul Airport Ist nerede?',
  'q_ivory_coast': 'Ivory Coast nerede?',
  'q_johan_cruyff_arena_home_of_ajax': 'Johan Cruyff Arena Home Of Ajax nerede?',
  'q_john_f_kennedy_international_airport_jfk': 'John F Kennedy International Airport Jfk nerede?',
  'q_kampala': 'Kampala nerede?',
  'q_kathmandu': 'Kathmandu nerede?',
  'q_kiribati': 'Kiribati nerede?',
  'q_kosovo': 'Kosovo nerede?',
  'q_kyrgyzstan': 'Kyrgyzstan nerede?',
  'q_la_bombonera_home_of_boca_juniors': 'La Bombonera Home Of Boca Juniors nerede?',
  'q_la_sagrada_familia': 'La Sagrada Familia nerede?',
  'q_landmark_81': 'Landmark 81 nerede?',
  'q_laos': 'Laos nerede?',
  'q_lesotho': 'Lesotho nerede?',
  'q_liberia': 'Liberia nerede?',
  'q_liechtenstein': 'Liechtenstein nerede?',
  'q_lima': 'Lima nerede?',
  'q_london_famous_for_fish_and_chips': 'London Famous For Fish And Chips nerede?',
  'q_london_heathrow_airport_lhr': 'London Heathrow Airport Lhr nerede?',
  'q_los_angeles_international_airport_lax': 'Los Angeles International Airport Lax nerede?',
  'q_lotte_world_tower': 'Lotte World Tower nerede?',
  'q_lusail_stadium_the_2022_world_cup_final_venue': 'Lusail Stadium The 2022 World Cup Final Venue nerede?',
  'q_maine': 'Maine nerede?',
  'q_malawi': 'Malawi nerede?',
  'q_maldives': 'Maldives nerede?',
  'q_mali': 'Mali nerede?',
  'q_malta': 'Malta nerede?',
  'q_manila': 'Manila nerede?',
  'q_maracanã_the_iconic_world_cup_venue': 'Maracanã The Iconic World Cup Venue nerede?',
  'q_marina_bay_sands': 'Marina Bay Sands nerede?',
  'q_mauritania': 'Mauritania nerede?',
  'q_mauritius': 'Mauritius nerede?',
  'q_metlife_stadium_near_new_york_city': 'Metlife Stadium Near New York City nerede?',
  'q_mexico_city_famous_for_tacos': 'Mexico City Famous For Tacos nerede?',
  'q_micronesia_federated_states_of': 'Micronesia Federated States Of nerede?',
  'q_montreal_famous_for_poutine': 'Montreal Famous For Poutine nerede?',
  'q_mozambique': 'Mozambique nerede?',
  'q_nairobi': 'Nairobi nerede?',
  'q_namibia': 'Namibia nerede?',
  'q_nauru': 'Nauru nerede?',
  

  // Kalan eksik çeviriler (2. batch)
  'q_neuschwanstein_castle': 'Neuschwanstein Castle nerede?',
  'q_new_delhi_famous_for_butter_chicken': 'New Delhi Famous For Butter Chicken nerede?',
  'q_new_hampshire': 'New Hampshire nerede?',
  'q_new_york_state': 'New York State nerede?',
  'q_niger': 'Niger nerede?',
  'q_north_dakota': 'North Dakota nerede?',
  'q_north_macedonia': 'North Macedonia nerede?',
  'q_old_trafford_the_theatre_of_dreams': 'Old Trafford The Theatre Of Dreams nerede?',
  'q_one_world_trade_center': 'One World Trade Center nerede?',
  'q_ottawa': 'Ottawa nerede?',
  'q_palau': 'Palau nerede?',
  'q_palestine': 'Palestine nerede?',
  'q_papua_new_guinea': 'Papua New Guinea nerede?',
  'q_paris_charles_de_gaulle_airport_cdg': 'Paris Charles De Gaulle Airport Cdg nerede?',
  'q_rhode_island': 'Rhode Island nerede?',
  'q_rio_de_janeiro_famous_for_feijoada': 'Rio De Janeiro Famous For Feijoada nerede?',
  'q_riyadh': 'Riyadh nerede?',
  'q_rwanda': 'Rwanda nerede?',
  'q_saint_basil': 'Saint Basil',
  'q_samoa': 'Samoa nerede?',
  'q_san_francisco_international_airport_sfo': 'San Francisco International Airport Sfo nerede?',
  'q_san_marino': 'San Marino nerede?',
  'q_san_siro_giuseppe_meazza_the_iconic_milan_stadium': 'San Siro Giuseppe Meazza The Iconic Milan Stadium nerede?',
  'q_santiago': 'Santiago nerede?',
  'q_santiago_bernabéu_home_of_real_madrid': 'Santiago Bernabéu Home Of Real Madrid nerede?',
  'q_seychelles': 'Seychelles nerede?',
  'q_sierra_leone': 'Sierra Leone nerede?',
  'q_signal_iduna_park_home_of_the_yellow_wall': 'Signal Iduna Park Home Of The Yellow Wall nerede?',
  'q_singapore_changi_airport_sin': 'Singapore Changi Airport Sin nerede?',
  'q_somalia': 'Somalia nerede?',
  'q_south_dakota': 'South Dakota nerede?',
  'q_south_sudan': 'South Sudan nerede?',
  'q_stade_de_france_the_national_stadium_of_france': 'Stade De France The National Stadium Of France nerede?',
  'q_suriname': 'Suriname nerede?',
  'q_são_tomé_and_príncipe': 'São Tomé And Príncipe nerede?',
  'q_table_mountain': 'Table Mountain nerede?',
  'q_taipei_101': 'Taipei 101 nerede?',
  'q_tajikistan': 'Tajikistan nerede?',
  'q_tehran': 'Tehran nerede?',
  'q_the_alhambra': 'The Alhambra nerede?',
  'q_the_blue_lagoon_in_iceland': 'The Blue Lagoon in Iceland nerede?',
  'q_the_central_african_republic': 'The Central African Republic nerede?',
  'q_the_chrysler_building': 'The Chrysler Building nerede?',
  'q_the_cn_tower': 'The Cn Tower nerede?',
  'q_the_colosseum_in_mexico_city': 'The Colosseum in Mexico City nerede?',
  'q_the_democratic_republic_of_the_congo': 'The Democratic Republic of the Congo nerede?',
  'q_the_gambia': 'The Gambia nerede?',
  'q_the_gateway_arch': 'The Gateway Arch nerede?',
  'q_the_golden_gate_bridge': 'The Golden Gate Bridge nerede?',
  'q_the_home_of_neapolitan_pizza': 'The Home of Neapolitan Pizza nerede?',
  'q_the_kingdom_centre': 'The Kingdom Centre nerede?',
  'q_the_lakhta_center': 'The Lakhta Center nerede?',
  'q_the_leaning_tower_of_pisa': 'The Leaning Tower of Pisa nerede?',
  'q_the_marshall_islands': 'The Marshall Islands nerede?',
  'q_the_netherlands': 'The Netherlands nerede?',
  'q_the_philippines': 'The Philippines nerede?',
  'q_the_republic_of_the_congo': 'The Republic of the Congo nerede?',
  'q_the_shanghai_tower': 'The Shanghai Tower nerede?',
  'q_the_shard': 'The Shard nerede?',
  'q_the_solomon_islands': 'The Solomon Islands nerede?',
  'q_the_turning_torso': 'The Turning Torso nerede?',
  'q_the_united_arab_emirates': 'The United Arab Emirates nerede?',
  'q_the_united_kingdom': 'The United Kingdom nerede?',
  'q_timor-leste': 'Timor-Leste nerede?',
  'q_togo': 'Togo nerede?',
  'q_tokyo_haneda_airport_hnd': 'Tokyo Haneda Airport Hnd nerede?',
  'q_tokyo_the_home_of_sushi': 'Tokyo The Home Of Sushi nerede?',
  'q_tonga': 'Tonga nerede?',
  'q_turkmenistan': 'Turkmenistan nerede?',
  'q_tuvalu': 'Tuvalu nerede?',
  'q_uganda': 'Uganda nerede?',
  'q_uluru_ayers_rock': 'Uluru Ayers Rock nerede?',
  'q_valencia_home_of_paella': 'Valencia Home Of Paella nerede?',
  'q_vanuatu': 'Vanuatu nerede?',
  'q_vatican_city': 'Vatican City nerede?',
  'q_vermont': 'Vermont nerede?',
  'q_vienna_famous_for_wiener_schnitzel': 'Vienna Famous For Wiener Schnitzel nerede?',
  'q_washington_dc': 'Washington Dc nerede?',
  'q_washington_state': 'Washington State nerede?',
  'q_wellington': 'Wellington nerede?',
  'q_wembley_stadium_the_home_of_football': 'Wembley Stadium The Home Of Football nerede?',
  'q_west_virginia': 'West Virginia nerede?',
  'q_willis_sears_tower': 'Willis Sears Tower nerede?',
  'q_wyoming': 'Wyoming nerede?',
  'q_zambia': 'Zambia nerede?',
  'q_zimbabwe': 'Zimbabwe nerede?',
  
  // NOT: Kalan 400+ soru için fallback mekanizması çalışacak
  // Çeviri yoksa orijinal İngilizce soru gösterilecek
};
